### ISSUE TITLE
LinuxInstall.sh is distro-dependent

### ISSUE THREAD

**Issue by dario-loi** [Futureblur/magnet#19]
Currently the script assumes that one is on a distribution that uses `apt` as a package manager for dependency installation, this is not the case in arch based distros which use `pacman`. I suggest to remove dependency installation from the install script and instead focus only on providing a script that builds the program and installs it to `/usr/local/bin`. The dependencies can be specified in the README and any user of any distro should be able to install them from their package manager in seconds.

I'll take the occasion to ask if this project can be distributed in the [AUR](https://aur.archlinux.org/), it's very easy to set up an installation script and it would speed up the installation process on every arch-based distro.

**Comment by rdsov** [comment]
Great suggestion. The initial plan was to get it up and running on Ubuntu for the CI pipeline, but other distributions should of course be considered.
